### ISSUE TITLE
Similarity feature

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#106]
Add a similarity feature that attempts to minimize duplicates by suggesting exisiting data objects when new ones are created. Applicable to:
- [x] People creation - search for people with a similar name
- [x] Locations creation - search for locations with a similar name
- [x] Positions creation - search for positions with a similar name

Initially we will do a simple text search when creating one of these objects and show matches as "Possible duplicates".

Later refinement might include:
- [ ] Better fuzzy matching by using similarity queries supported by the underlying database
- [ ] Match locations within a close geo distance

**Comment by dspCarlson** [comment]
This did not test successfully.  The domain user name is not set to NULL when inactivating a person.  Furthermore, the domain user name should only be set to NULL for domain user names that are role-based.  Three networks use role-based domain user names.  One network creates domain user names based on the user's name, not their role.

**Comment by VassilIordanov** [comment]
I like how github does this. When creating an issue, it brings a "The following issues might be related."
We can do this when creating new items
