### ISSUE TITLE
Epic 1078 - ANET Messages

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#1078]
Implement messages in ANET:
- [x] Find a good name. Messages/Notes/Comments/Posts?
- [x] Implement data model. A message should consist of:
  - a body of content (for now draft.js html/json)
  - a list of UUIDs of related objects
- [x] Add related messages to any page of content that is tagged
- [x] Add UI for entering messages. It should be accessible from any page with a UUID - automatically populates the UUID. Possibly this should bring an inline editor

Next phase would be #1129
