### ISSUE TITLE
Epic 1115 - Subscriptions

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#1115]
- [x] maintain per position a list of UUIDs to which he/she has subscibed (was NCI-Agency/anet#1344)
- [x] update subscriptions when an object is updated (was NCI-Agency/anet#1368)
- [x] add a follow/unfollow button to any item with an UUID (was NCI-Agency/anet#1369)
- [x] show 'my subscriptions' on the home page (was NCI-Agency/anet#1370)
- [x] add a "my feeds" page. It should contain
  - [x] a chronological list (most recent on top) of
    - [x] any note that references an item to which a user has subscribed
    - [x] any report that references such items

Perhaps at a later stage, system messages related to change of state of tracked object (i.e. report is approved).

**Comment by VassilIordanov** [comment]
Proposal of how should "events" be constructed at the first phase of implementation:

all lists are chronological, newest first

Person: list combining:
      - all published (including cancelled) reports of which the person has been the author or attendee
      - all notes posted on that person

Position: list combining:
      - all published (including cancelled) reports of which the person in that position has been the author or attendee
      - all notes posted on that pesition

Organization: list combining:
      - all published (including cancelled) reports of this org
      - all notes posted on that org

Task: list combining:
      - all published (including cancelled) reports citing this task
      - all notes posted on that task

Report: not sure yet

Authorization group : not sure yet



Location
      - all published (including cancelled) reports with this location
      - all notes posted on that location

My feed:
     - a list of all event I have subscribed to
     - with ability to filter by type (People / Locations / ...)
