### ISSUE TITLE
Epic 1078: ANET Messages phase 2

### ISSUE THREAD

**Issue by gjvoosten** [NCI-Agency/anet#1129]
Next phase after #1078 would be:
- [x] allow linking of notes to entities/UUIDs selected by the user
- [x] show additional entities/UUIDs that a note is linked to
- [ ] allow user to create a new message from the top menu (similar to Create New Report, etc.) and link it to selected entities/UUIDs

Also:
- [ ] something like a "My Notes" page listing all the notes by the current user?
- [ ] perhaps convert existing report comments to messages?
