### ISSUE TITLE
Epic 17 - Ability to tag reports with keywords

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#17]
Reference items 4 and 20

- [ ] Keyword administration UI (was #108)
- [x] #109 
- [x] #126 
- [x] #127 
- [ ] Suggestions for report tags (was #128 )
The suggestions shown for tags currently do a simple string match in the complete list of tags.
Suggestions (as in ANET suggestions like implemented for People, Places, etc) should come from two sources:
    - Tags with a match in the already entered text in other fields such as description
    - Frequently used tags by the user
- [ ] Relations between tags (was #129 )
- [x] #137 
- [ ] Add documentation about adding report tags (was #145 )
- [ ] Add a tag selection widget (was #152 )
A tag selection widget should provide:
  - [ ]  a hierarchical way to browse tags
  - [ ]  it should show the description of the tag under selection
  - [ ]  if a tag is not in the list, the user should not be able to add a new tag
Maybe we can use the advanced select widget for this?
- [ ] Migration of old reports to be done with tools developped in #107. In normal operation, the tagging of already published reports should not be altered

Initial functionality is:
A list of keywords to be added to the data initially without the help of an UI. 
#108 to improve that at a later stage.

Keywords have the following properties:
- name
- description
Later it should be possible to have relations between tags: Is-a relationship to other keyword(s). Is-a is a directional relationship

When drafting a report, a user can tag a report with a keyword. Frequently used keywords to be suggested to user.

A tag should be rendered with # preceding it and on a rounded edge background. Tooltips should be displayed when clicked or (to support phone usage) or possibly also mouse-over events (todo: create a separate story for general tooltips)

Searching for keywords could be done by the search or via a custom search #109. Any report tagged with a keyword has a Is-a relationship with the search subject

Later

**Comment by gjvoosten** [comment]
Define who can add new tags (role-based).
Decide whether tags are e.g. hierarchical.
Perhaps tags also needs a description/explanation (e.g. in the form of tooltips).
Does adding a tag also add tags from the hierarchy, or does e.g. the search include it?

**Comment by dspCarlson** [comment]
1. Only users in the administrators group should be able to add and remove key words.

2. Yes, tags should be hierarchical.  For example, two tags are displayed: "car" and "tire."  If "tire" is selected by the user, a query of "car" would return the record associated with "tire."

3. Tool tips?  Yes!  Great idea!  Can these tool tips be edited by the administrators?

4. When a child tag is chosen, the parent tag does not have to be included for that record.  A query will find the hierarchical parents.

**Comment by gjvoosten** [comment]
I'm going to make separate issues for:
- relations between tags
- styling of tags in the UI
- tooltips for the tags
- suggested tags

**Comment by VassilIordanov** [comment]
After loading newReport page, focus is in Tags field, instead of Meeting Goal

**Comment by gjvoosten** [comment]
The documentation is a bit unclear:
https://www.npmjs.com/package/react-tag-input#autofocus
but apparently, `true` is the default and not `false`. 🙁

**Comment by gjvoosten** [comment]
I'll set `autofocus` to `false` so the tags field doesn't take focus, but note the Meeting Goal field doesn't take focus (it also didn't take focus before #130 was merged).

**Comment by VassilIordanov** [comment]
On IE11, on the staging server, the tag UI is not working. I suggest we replace it with a simple menu that allows to pick a tag.

**Comment by gjvoosten** [comment]
@VassilIordanov Have the (default) tags been loaded in the database? No tags = no suggestions.

**Comment by VassilIordanov** [comment]
@gjvoosten - correct. It seems like they got overwritten at some point (possibly when copying production into staging db). I've pushed the tags and it is working now.

**Comment by dspCarlson** [comment]
@VassilIordanov @gjvoosten I inserted 12 tags and tested the key word functionality.  It works great.  There was one inconsistency in the drop down list.  Sometimes it is no longer displayed after three seconds when left alone and sometimes it is no longer displayed after 15 seconds.  I was not able to consistently recreate the two scenarios to know what triggered both scenarios.  But the word tagging is great as is the announcement banner which is fantastic.

**Comment by dspCarlson** [comment]
@VassilIordanov also created/saved a SQL script to re-insert the 12 test key tags should the staging database need to be refreshed again.

**Comment by VassilIordanov** [comment]
Alas, tags have not been that effective. Time to rethink
