### ISSUE TITLE
Epic 1706 - Organization Hierarchy

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#1706]
- [x] Users should see an org chart on each organization page. The org chart should represent the hierarchy of that organizations, as well as the positions
- [ ] Users should see a counterpart org chart on each organization. Same as above, but for the counterparts of that org
- [ ] Users should see an org chart for report collections - organizations that have been part of the engagements should be shown, as well as statistics on the number of reports
- [ ] assessment progress should be shown on org charts for both advisors and principals. 
  - [ ]  green icon = assessed (by) all counterparts in the past month
  - [ ]  yellow icon = assessed (by) all some in the past month
  - [ ]  red icon = assessed (by) none some in the past month
- [ ] an org hierarchy should be used when selecting orgs, positions or people from advanced autosuggest

**Comment by midmarch** [comment]
Related to [branch GH-1706-better-org-diagram](https://github.com/NCI-Agency/anet/tree/GH-1706-better-org-diagram)

**Comment by gjvoosten** [comment]
Obsoleted by #5098
