### ISSUE TITLE
Epic 1704: Add future engagements planning workflow

### ISSUE THREAD

**Issue by maradragan** [NCI-Agency/anet#1722]
Right now it is enough to fill in only a future date for an engagement and it becomes a future engagement.
We currently display future engagements as follows in ANET:
a) on the upcoming engagements dashboard:
    - for a normal user: the upcoming engagements of his organization
    - for an admin: all upcoming engagements
b) on the My Reports page
    - the current user's future engagements
c) we can search for them by state
    - like this we can get future engagements of other users, which maybe have only filled in a date
d) in the future engagements insight

But, a user might also just want to first draft a future engagement: 
- he/she only has some rough ideas about a future engagement he/she plans to have but not all information is available
- or maybe the planning is not finalized (the timestamp and the location of an engagement need to be confirmed in the planning, maybe the attendees need to confirm their attendance?)

This is not possible right now (or at least, one can't say whether the information is draft or not). 
Therefore one can not say whether the information from a future engagement is "final" or not, and maybe we should only publish "final" information in ANET, at least when it concerns engagements of others.
In order to make it clear whether the information in a future engagement is draft or not, future engagements should also go through an approval workflow.

This means that future engagements should also be "submitted"/"reviewed" (do we maybe need a different term for it, like "plan" instead of "submit"?) and go through different states: draft, pending approval, rejected, published.

The publication approval workflow for engagements which already took place should be different of the planning approval workflow of future engagements. Therefore, on the organization page we split the approval process in 2:
- Engagement planning approval process
- Report publication approval process
An approval step than gets a type: public enum ApprovalType { PLANNING_APPROVAL, REPORT_APPROVAL }

On a report show page we will display the planning and the publication workflow actions which took place as if it would be one workflow, in one section.

Questions about the future engagements workflow:
- [x] do we need a different term for submitting future reports for approval? => not for now
- [x] do we maybe need a "draft future", "pending approval future" state, in order to be able to search - for them? => no
- [x] should the approval workflow for future engagements be the same as the one for reports which already took place? I would think that for future reports we might need different approval steps (example: planning approval step, content approval step) and that an organization might have different people responsible for the approval of future reports than the people responsible with approving the engagements which already took place. => different workflows, on the organization level 2 sets of approval steps need to be specified
- [x] for upcoming engagements reports, they only go till the "approved" state as it should always be possible to edit them.
- [x] change the visibility rules: when searching for reports one can get as results approved and published reports for which he/she is not the author of.
- [x] when can future engagements be edited and what should happen with the state when they are being edited? => The rules for being allowed to edit a report should change (no matter the engagement status):

   - authors can edit a report at any time before the report is being published; after editing the report gets back to draft;
   - approvers can only edit reports being in an approval step they belong to; the report doesn't go back to draft in this case;

- [x] just as now, after an engagement has gone from future to already have taken place, its report gets the status draft and from here on everything stays the same as before, the report needs to go through the report approval process
- [x] let's say that we have an upcoming engagement which is submitted by it's author. The first approvers get an e-mail. But they don't do anything with it yet and in the meanwhile the engagement becomes a past engagement and therefore the report gets back to the DRAFT state. Now one of the approvers finally clicks on the link in the old approval needed email ... well the report doesn't need approval any more, so what should we do about it? => we don't do anything about it, the approver can see the new report status on the report page.
- [x] what if the report of a future engagement has been rejected during the planning approval? Should it stay rejected or should it become draft when becoming a past engagement? => should become draft
- [x] maybe we need to add a search filter for reports: is future, so that the user has the possibility to have a saved search for upcoming engagements with a specific filter he/she needs => we will add an engagement_status query arg to the GraphQL.
- [x] what about the migration of all current future engagements reports? Should we replace the future state with draft for all existing future reports and send an e-mail to the author? => we will replace it with draft and not send any e-mail to the authors. After the deployment of the new functionality an e-mail with details about the new release will be sent (manual action).
- [x] when is a report considered for a future engagement? => A report is considered for future engagement when       
```
 engagementDate &&
       moment()
         .endOf("day")
         .isBefore(engagementDate)
```

Part of #1704 epic

**Comment by VassilIordanov** [comment]
What if we change our terminology a little. Let's say we rename reports to engagements.
- So a user can click on "new Engagement"
- An engagement in the future is an "Engagement plan"
- An engagement in the past becomes an "Engagement report"

Then would it help if we split the state in 2 independent state variables (approval state and engagement status terminology is a bit nobly for now, I agree...)

Engagement_Approval_State
  DRAFT
  PENDING_APPROVAL
  REJECTED
  APPROVED
  PUBLISHED

Engagement_Status
  PLANNED
  REPORTED
  CANCELLED

So when a user creates an engagement - the status is determined by the date - PLANNED or REPORTED

If REPORTED - same behavior as now

If PLANNED - goes through a similar process as a reported engagement for a different approval chain for the same org (maybe by skipping APPROVED as you suggest). Then the date of the engagement, the engagement becomes reported, and its status is moved to draft.

Another option is to keep the planned engagements and the engagement reports as separate objects (2 different UUIDs) and have the report reference the planned engagment if there was one.

**Comment by maradragan** [comment]
I think it's good to split the state.

**Comment by maradragan** [comment]
About having planned engagements as a different object, I would  say no, it would overcomplicate the things.

**Comment by maradragan** [comment]
About the state: I think it's best if we no longer use the FUTURE and CANCELLED states, we can just derive them from the engagementDate and from the cancelledReason.
