### ISSUE TITLE
Epic 1704: Add engagements calendar

### ISSUE THREAD

**Issue by maradragan** [NCI-Agency/anet#1723]
Use a calendar widget to display the engagements.

Basic features of the calendar component:
- [x] Month, week, day views
- [x] prev/next navigation
- [x] select today
- [x] display all events with the same style and same details in all views
- [x] On click on a date, go to the day view of that date
- [x] On click on an event, go to event show page

Where to use the calendar component on?
- [x] On every page where there is a report list, add a Calendar tab: (Calendar | Summary | Table | Map)
- [x] Make sure they also contain future engagements

- [x] Add list view (see the list option here: https://fullcalendar.io/#demos)
- [x] Per view type, it should be possible to define a max number of items to display
- [x] Display the total number of items (or, maybe better, display a link with "x more...")
- [x] Display reports as being full-day event when no duration available

**Comment by VassilIordanov** [comment]
I suggest the following features:

- responsive

- Render a calendar with the following views
  - weekly view
  - past, current and next week view
  - monthly view

Display a collection of dated items (most likely reports)
