### ISSUE TITLE
Epic 1773 - Improve rich text component

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#1773]
- [x] Currently, the rich text toolbar looks like a html editor. Users would be more comfortable with a toolbar that is similar to rich text editors. 
- [x] ~~Users have reported that spellchecking works in normal text fields but not in the rich text editor. Maybe it is a matter of simply turning `spellCheck` to `on` - worth investigating~~ https://github.com/facebook/draft-js/issues/640
- [ ] Users would like the ability to add references to other ANET objects in the body of the text (specifically other reports and people). We can experiment with adding a mention/link to anything that has a UUID in ANET (except for notes), possibly by using an advanced auto-suggest chooser. See #1811

**Comment by evdhoudt** [comment]
Notes:
- https://www.draft-js-plugins.com/plugin/mention
- https://www.draftail.org/docs/getting-started-with-extensions

Feature  description for adding people

As an Author 
I want to add a mention to another person
So that I can reference other people in the report

Scenario 1: 
Given the Author is writing in a rich text editor
When the author types @
Then a popup menu unfolds with suggestions of people based on their name
And when the author keeps on typing
the menu filters the suggestions to fit the typed name

**Comment by jose-west** [comment]
After the team meeting we decided to merge all components into a single modal. It should work just like the current implentation of the AdvancedSelectComponent, but with the addition of the search bar and filter buttons at the top.
We should also explore the possibility of rendering links as LinkTo components, instead of plain HTML.
