### ISSUE TITLE
Epic 1963 - Code cleanup

### ISSUE THREAD

**Issue by maradragan** [NCI-Agency/anet#1963]
- [ ] Address Java checkstyle warnings #1521
- [x] Address Javascript eslint warnings #1522
- [x] Remove selenium tests #1573
- [x] Replace abandoned `webpack-cleanup-plugin` with `clean-webpack-plugin` ( https://github.com/johnagan/clean-webpack-plugin , to get rid of the _DeprecationWarning: Tapable.plugin is deprecated._ ); see https://webpack.js.org/guides/output-management/#cleaning-up-the-dist-folder
