### ISSUE TITLE
Epic Admin users usability improvements

### ISSUE THREAD

**Issue by maradragan** [NCI-Agency/anet#1965]
- [ ] Powershell scripts (was #907)
Create a graphql-based API to ANET.
Add some common admin srcipts
- [ ] Change the banner "General banner level" input from text to a drop down menu (was #586)
The "General banner level" has four parameters that change the color of the banner. The four parameters must be typed in. Instead of typing the values into a text box, the four values should be displayed in a drop down menu.
Instead of displaying the four parameter values of "Error," "Notice" etc, just display the banner color (i.e. red, blue, green and yellow) as drop down values.
The "General banner level" only affects the banner color. It does not change the banner's default wording. The banner's default wording is "Announcement:"
- [ ] Change the banner "General banner visibility" input from text to a drop down menu (was #587)
The  "General banner visibility" parameter accepts three numerical values  that must be typed in.  Change the inputted value to a drop down menu. The three values are:
1 - Users only
2 - Super users and administrators only
3 - Users, super users and administrators
- [ ] Banner does not change color when the "General banner level" parameter is changed (was #585)
When an existing banner is displayed, the color does not change when changing the "General banner level" parameter.
The work around to change the banner color is to:
    - Change the "General banner level" value
    - Select the "Save settings" button
    - Change the "General banner visibility" value to "1"
    - Select the "Save settings" button
    - Change the "General banner visibility" value again
    - Select the "Save settings" button again
- [ ] GraphQL admin interface (was #824)
Enhance the current graphiql interface to permit saving/loading queries
Ideally, admins should be allowed to save/share queries, and eventually compile a toolbox of queries/mutations for data maintenance that is not possible yet through the UI
see discussion here: apollographql/apollo-client-devtools#16

- [ ] Markdown support for banner (was #312)
Add the ability to insert markdown formatted text into the banner. Mostly useful for hyperlinks.
