### ISSUE TITLE
Epic1968 - Improve performance

### ISSUE THREAD

**Issue by maradragan** [NCI-Agency/anet#1968]
- [ ] First make it possible to test in development with enough data
We therefore have to implement a simulator to generate a lot of data: see #379
- [ ] Improve simulator (see #2347)
- [ ] Find out why is the application slow?
- [ ] Instrumentation
...
