### ISSUE TITLE
Epic 1969 - Full text search

### ISSUE THREAD

**Issue by maradragan** [NCI-Agency/anet#1969]
- [ ] Configure full text search filter for html content (was #1650)
The fts search returns many false positives as it matches the html tags of rich text fields. Enable filters for such content
https://docs.microsoft.com/en-us/sql/relational-databases/search/configure-and-manage-filters-for-search?view=sql-server-2017

- [ ] Review behavior of search text indexing and ordering (was #1497)

`H` - high weight
`L` - low weight

Search/indexing behavior by type:

`exact`
  - match only if there is an exact match. Could be fts but it doesn't have to be
  - not sure how to deal with exact matched for terms containing a space, possibly to require quoted search expression...

`startWith`
  - match also partial cases, i.e. if first 4 characters or more are an exact match. Could be fts but it doesn't have to be

`fts name` 
  - full text search 
  - full word matches (no partial matches by default)
  - accent and capitalization insensitive
  - fuzzy search for misspelling and/or phonetic similarity (but possibly with a lower rank if fuzzy match)
  - insensitive to `-` and to `'` - `van-iordanov`, `van'iordanov`,  `vaniordanov` or `van iordanov` should all be able to match `van-iordanov`, `van'iordanov`,  `vaniordanov` or `van iordanov`. 
  - nice to have: 
    - multiple language support for english and arabic
    - partial match support with wildcard `*/?` syntax

`fts text`
  - full text search 
  - full word matches (no partial matches by default)
  - stemming
  - accent and capitalization insensitive
  - fuzzy search for misspelling (but possibly with a lower rank if fuzzy match)
  - nice to have: 
    - multiple language support for english and arabic
    - partial match support with wildcard `*/?` syntax

ranking: 
  - results matching a high ranking field are on top. 
  - results matching a high ranking field with a fuzzy match are lower. 
  - results matching a low ranking field are last

Search expressions with more than one term:
- searches for several words act as `and`
- ranking is the product of the rankings of all terms (highest if all terms rank high)
- nice to have: 
  - searches for n words feature results that match all n words but also feature results that match a subset of (n-1) words at a lower rank
  - some kind of optional syntax such as google's to support `OR` as well as excluding a term

Report
    - UUID `H startWith`
    - summary `H fts text`
    - nextSteps `H fts text`
    - keyOutcomes `H fts text`
    - reportText `L fts text`
    - notes `L fts text`
    - ~attendees names `L fts name`~ (use the advanced search filter for that)
    - ~task `L fts text`~ (use the advanced search filter for that)

Person
    - UUID `H startWith`
    - name `H fts name`
    - position name `H fts text`
    - position post number `H exact`
    - position's organization identificationCode `H exact`
    - position's organization short name `H exact`
    - domainUsername `H exact`
    - email `H exact`
    - phone `H exact`
    - biography `L fts text`
    - notes `* L fts text`

Position
    - UUID `H startWith`
    - name `H fts text`
    - post number `H exact`
    - person's name `H fts name`
    - ~names of previous people in that positions `L fts name`~ (is this really needed?)
    - position's organization identificationCode `H exact`
    - position's organization short name `H exact`
    - notes `L fts text`

Task
    - UUID `H startWith`
    - short name `H exact`
    - long name `H fts text`
    - notes `L fts text`

Location
    - UUID `H startWith`
    - name `H fts name`
    - notes `L fts text`

Tag
    - UUID `H startWith`
    - name `H fts text`
    - description `L fts text`
    - ~notes `L fts text`~ (tags don't have notes)

Organizations
    - UUID `H startWith`
    - identificationCode `H exact`
    - short name `H exact`
    - long name `H fts text`
    - notes `L fts text`

Authorization Groups
    - UUID `H startWith`
    - name `H fts text`
    - description `L fts text`
    - notes `L fts text`

- [ ] When searching by principal position code, entering the UIC, should only return principal positions with that UIC.
Entering a hyphen and then a paragraph number should only return principal positions with the UIC and paragraph number.

- [ ] Advanced search does not find principal's first name  (was #1053 )
A user couldn't find a principal's record searching by first name. I was able to replicate the bug.
Test 1
I used Advanced search (with the "People" parameter) and entered the last name. The search results returned the principal's record.
Test 2
I used Advanced search (with the "People" parameter) and entered the first name. The search results did not return the principal's record. In fact, none of the 24 returned results contain the principal's name. There are 74 principal records which have the first name as part of a principal's name. The first name can also be used as a last name.
Test 3
I used the first name in a general search without any parameters and the same 24 principal records were returned at Test 2 (along with 3,929 engagement reports).
Test 4
I used Advanced search (with the "People" parameter and a "Role" = principal) and entered the first name. The search results did not return the principal's record. In fact, none of the 24 returned results contain the principal's name. The same search results as Test 2.
I have sent the principal's full name to @VassilIordanov on the high side.

- [ ]  Make autosuggest for position be also searchable by the currently (or last) occupying person's name (was #544)

**Comment by gjvoosten** [comment]
Can you give some real-world examples of expectations (like https://github.com/NCI-Agency/anet/issues/1053 ) that would make at least for some reasonable test material?
So examples of what should and shouldn't match, to be able to test whether the current set-up is OK (which has a trigram index for UUID prefix matches and a full-text index for the given relevant columns/aggregations for each object; see below for details on the current implementation).
Also possibly some scenarios that people currently use to work around issues of not being able to find stuff.

UUID matching: what should happen in a case such as the following: search for the text `"cafe babe" abba -deaf OR added face -"dead beef"`?
Currently, the the PostgreSQL PoC would add a clause `uuid ILIKE '"cafe babe" abba -deaf OR added face -"dead beef"%'` but that is probably not the most useful thing to do.

The current implementation on MS SQL has an e2e test searching locations for `general hospita` and expects it to match `General Hospital` (not true for the PostgreSQL PoC).
The server-side (Java) tests also have some expectations, e.g. that searching organizations for `EF 1` will also match `EF 1.1` (not true for the PostgreSQL PoC).
Should these still match or not?

This issue specifies that people search should also search through positions, and positions search should also search through people. Currently, there are search query properties like `PersonSearchQuery::matchPositionName` and `PositionSearchQuery::matchPersonName` that are not user-selectable (they are set for the advanced select, and not set for the general search). The PostgreSQL PoC no longer use these props (basically it is always done), so should we drop these props?

Current implementation in the PostgreSQL PoC:

**Notes**
• generated column `full_text`: `text` _'B'_

**Authorization Groups**
• generated column `full_text`: `name` _'A'_, `description` _'B'_
• prefix match: `uuid`
• full-text match: MV on `full_text`, aggregated `notes.full_text`

**Locations**
• generated column `full_text`: `name` _'A'_
• prefix match: `uuid`
• full-text match: MV on `full_text`, aggregated `notes.full_text`

**Organizations**
• generated column `full_text`: `identificationCode` _'A'_, `shortName` _'A'_, `longName` _'B'_
• prefix match: `uuid`
• full-text match: MV on `full_text`, aggregated `notes.full_text`

**People**
• generated column `full_text`: `name` _'A'_, `domainUsername` _'A'_, `emailAddress` _'A'_, `phoneNumber` _'A'_, `biography` _'B'_
• prefix match: `uuid`
• full-text match: MV on `full_text`, aggregated current `positions.full_text`, aggregated current position's `organizations.full_text`, aggregated `notes.full_text`

**Positions**
• generated column `full_text`: `code` _'A'_, `name` _'A'_
• prefix match: `uuid`
• full-text match: MV on `full_text`, aggregated current `people.full_text`, aggregated `organizations.full_text`, aggregated `notes.full_text`

**Reports**
• generated column `full_text`: `intent` _'A'_, `keyOutcomes` _'A'_, `nextSteps` _'A'_, `text` _'B'_
• prefix match: `uuid`
• full-text match: MV on `full_text`, aggregated `notes.full_text`

**Tags**
• generated column `full_text`: `name` _'A'_, `description` _'B'_
• prefix match: `uuid`
• full-text match: MV on `full_text`

**Tasks**
• generated column `full_text`: `shortName` _'A'_, `longName` _'B'_
• prefix match: `uuid`
• full-text match: MV on `full_text`, aggregated `notes.full_text`

Delay between materialized view refreshes in the PostgreSQL PoC is now 60s.
Should we use more weight classes besides _'A'_ and _'B'_?

**Comment by VassilIordanov** [comment]
In order of importance:

essential
- if a person "Smith, John" exists and I search for "John" or "Smith" or "John Smith" or "Smith John" I would expect a match
- if I have a person "John Smith" I expect that person to be a match for starting substrings "Joh" or "Sm", so I also expect `general hospita` or `hospita` to be a match for `general hospital` (
- given uuid `60f9be6f-59b8-44e0-927e-1bb56dbf3f42` the search should return when searched for exact value
- given uuid `60f9be6f-59b8-44e0-927e-1bb56dbf3f42` any substring should be a match for the autosuggest such as `60f9be6f` or `bb56dbf3f4`

would be great to have but can live without it until we decide what to do
- if I have a person "John Smith" I expect that person to be a match for starting substrings "Joh" or "Sm", so I also expect `general hospita` or `hospita` to be a match for `general hospital`
- if I have a person "John Smith" I expect that person to be a match for similar strings such as "Jon"

nice to have
- Usage of `"`, `-`, `OR` etc is not a requirement. It won't hurt to have it, especially wildcards, but not required

**Comment by gjvoosten** [comment]
There seems to be duplication in:

> essential
> 
> * if I have a person "John Smith" I expect that person to be a match for starting substrings "Joh" or "Sm", so I also expect `general hospita` or `hospita` to be a match for `general hospital` (

and:

> would be great to have but can live without it until we decide what to do
> 
> * if I have a person "John Smith" I expect that person to be a match for starting substrings "Joh" or "Sm", so I also expect `general hospita` or `hospita` to be a match for `general hospital`

**Comment by gjvoosten** [comment]
Please describe which fields per object type you wish to include in substring matches (prefix, infix, suffix).
Please describe how you want to deal with searches like `Joh Smi hospital` where part of the search text matches some field of an object and another part of the search text matches some other fields of that object.
