### ISSUE TITLE
Epic 1971 - Infrastructure and deployment

### ISSUE THREAD

**Issue by maradragan** [NCI-Agency/anet#1971]
Automate windows service deployment (was #390)
- [ ] bundle ANET with https://nssm.cc/ and evaluate how that goes
- [ ] create an upgrade powershell scripts that does (possibly remotely)
    - upload `anet.X.X.XXX` distribution to remote server
    - stop ANET service with `net stop anet`
    - backup ANET database
    - move `{$ANET_DIST)/bin`, `{$ANET_DIST)/doc` and `{$ANET_DIST)/lib` to `c:\ANET\nackups\Upgrade_to_X.X.XXX` backup directory
    - unzip distribution into {$ANET_DIST)
    - execute `bin/anet check` and `bin/anet db migrate' 
    - start ANET service with `net start anet`
- [ ] update installation documentation

- [ ] Provision of infrastructure for anet application (was #122 )
Let's start with infrastructure to run a linux docker deployment of ANET builds of the candidate branch

- [ ] docker image for ANET application server (was #120 )

**Comment by VassilIordanov** [comment]
closed as we move to mostly support Linux. #120 is reopened
