### ISSUE TITLE
Epic - Persons management

### ISSUE THREAD

**Issue by maradragan** [NCI-Agency/anet#1972]
- [ ] Do not allow to save a person's record when all the letters in the first name are capitalized (was #902)
When saving an advisor's first name or a principal's first name, do not allow the person to be saved if all the letters of the first name are capitalized.
Display an error message stating "Given names / first names are not capitalized. Only the first letter of each given name / first name is capitalized"

- [ ]  Use the national HR system to identify principals (was #911)
This GH issue is for a future enhancement. If advisors can get the national ID number of the principal, the principal's name could be automatically populated and populated correctly.
Will the owner of the HR system let ANET use a periodic copy of the HR data?

- [ ] Revise principal pedigree/bio information structure (was #1014)
Add ethnicity, tribe, affiliation.....
Possibly hide nationality
@devin040 anything else?

- [ ] Standardize how principal names are inputted and how principal names are displayed (was #1104)
Principal names vary.  For example, some principals litter have one name.  Other principals have a name followed by their father's name.  Allow the super users to enter principal names based on the name formation.

Here are the name permutations for principal names:
1. One name only
2. Given name(s) and surname(s)
3. Given name(s) and surname(s) "son of" <father's surname>
4. Given name(s) and surname(s) "son of" <father's given name(s) and father's surname(s)>

Could a data entry template be created that takes these four permutations into consideration?  Principal names are all over the place when it comes to the "son of" names.

- [ ] Force Super Users to Enter an End of Tour Date When Setting a Principal's Status to "Inactive" (was #352)
When a super user sets a principal's profile to "Inactive," force the super user to enter an end of tour date when saving the profile.
Note: Principals have an end of tour date when they retire or are fired.
Reference item 129

- [ ] Remove Titles from Names When Saving the Name (was #202)
It seems like there is a list of titles that can't be easily confused with people's names. The suggestion is to add this list to the dictionary and have client-side validation that prevents a user from adding a name containing these. This applies to people creation and onboarding.
The validation error should be something along the lines of:
"You must provide a valid name without ranks, titles, and grades. %offendingValue% is not allowed in name fields"

**Comment by dspCarlson** [comment]
@maradragan RE: Use the national HR system to identify principals (was #911)
This is no longer a valid requirement as the national ID is not a consistent identifier.  Some principals have multiple national cards/ID numbers.  When a national ID card is lost, a new card is created with a new ID number.  Some principals are not willing to share their national ID number.
