### ISSUE TITLE
Epic 2206 - Trend indicators

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#2206]
- [x] Add rudimentary trend indicators (past 30d vs previous period)
- [ ] trends as a miniature graph activity
- [x] add them to dashboards
- [ ] add them to org charts
