### ISSUE TITLE
Epic 2957: Responsive behavior

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#2957]
ANET does render in a phone, as well as on a 4K screen. However, it designed with a desktop browser with HD screen resolution as a target. On any other environment, the layout is not optimal and user interaction is not tested.

As a user, I would like to be able to author and submit reports from a smart phone or tablet device in addition to a desktop computer. I expect the touch interface to be functional

As a user or a superuser I want to be able to perform most ANET functions from a phone or tablet device. I understand that some functionality might be limited due to screen real estate

As a super user and experienced user, I want to use ANET on a 4K desktop to visualize analytical products

**Proposed approach**
- [ ] perform a survey of the shortcomings of the user interface and identify specific areas that need improvement per component ( i.e. layout of all FormFields do not scale well when on big screen, or advanced search component does not work well with a touch screen)
- [ ] to be confirmed after initial study
- [ ] propose solutions and or technologies for addressing so (i.e. utilize `emotionjs` + `facepaint` to handle media queries, and/or structure React Components a certain way, etc). It should be ideally an incremental approach.

**Prior work**
see https://github.com/NCI-Agency/anet/issues/551 and also some items here: https://github.com/NCI-Agency/anet/issues/2293 and https://github.com/NCI-Agency/anet/issues/1964
