### ISSUE TITLE
Epic 2959: Data import and manipulation framework

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#2959]
**Is your feature request related to a problem? Please describe.**
Importing data into ANET is currently done on a case-by-case and one-off manner. A lot of work is done all over again and information may be missed

As an administrator, I would like to have some tools at my disposal that allow me to:
- quickly write scripts to import data in a single action. Common import sources include spreadsheet sources, infopath documents, XML, json, custom data
- write scripts to continuously import data. These tools should include ways to identify new data, vs modified data, vs deleted data. Common sources, besides the above, are directory services such as AD and LDAP, 3rd party databases
- write data maintenance scripts - detect data problems and repair data: eg, find user accounts with invalid data, orphaned objects, etc.
- be able to write future background anet scripts ( NLP processing, etc)

**Suggested approach**
- [ ] identify a data manipulation platform to be used (e.g.  https://pandas.pydata.org/)
- [ ] identify a way to implement python bindings for the ANET data model, possibly using an orm (ponyorm, django's orm....)
- [ ] create a proof of concept integration with ANET
- [ ] implement a selected example (available on demand in slack) as a proof of concept import script
- [ ] refine and finalize integration script 

**Examples**
- export a spreadsheet with people, orgs and positions to excel (each on a separate sheet)
- export a spreadsheet with tasks to excel
- import excel spreadsheets in the above formats
- reference uuids in excel spreadsheet to existing objects in ANET and update them
- for new objects, handle internal string identifiers and transgorm them into uuids
- after import, return an updated spreadsheet (with newly created uuids)
- implement the above as Excel -> ANET objects mappings, that could be extended to other data sources besides excel - AD, LDAP, etc...
- support the ability to track the id of foreign records (external database uids, etc) and the mapping to ANET uuids. Import can also remember a hash of the imported data to determine a change in the content.
- should be able to safely run in parallel with ANET (i.e. invalidate anet caches when needed, transactions, etc...)
- no UI needed besides logging

**Additional context**

User stories:

Epic PR: #3284

- [ ] Generate the core data model from the ANET data model #3485
- [ ] Make customizations of core objects that have the necessary business logic #3486
- [ ] Create the Import API on top of ANET objects #3487
- [ ] Provide example Python scripts using the API to import data #3488

**Comment by oayvazoglusim** [comment]
[epic2959.zip](https://github.com/NCI-Agency/anet/files/5074172/epic2959.zip)

**Comment by gjvoosten** [comment]
Replaced by specific scripting.
