### ISSUE TITLE
Ability to differentiate on location types

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#3547]
Note: Please read "Additional context" first.  "Additional context" is at the bottom of this issue.

**Is your feature request related to a problem? Please describe.**
Locations are being used indiscriminately.  For example, a principal position can have a location assigned that is actually an advisor location.  An advisor position can have a location assigned that actually is a principal position.

**Describe the solution you'd like**
Only allow the correct type of location to be chosen for specific use cases.

Requirements:
_Use case 1_: Creating/Editing an advisor position
A super user/admin should not be able to select a virtual location, a geographical location or a principal location when creating/editing an advisor position.  Only advisor locations should be available for selection.

_Use case 2_: Creating/Editing a principal position
A super user/admin should not be able to select a virtual location, a geographical location or an advisor location when creating/editing a principal position.  Only principal locations should be available for selection.

_Use case 3_: Selecting a location for an engagement report
When selecting an engagement location, a report author should be able to select a virtual location or a principal location or an advisor location.  The report author should not be able to select a geographical location.

_Use case 4_: Selecting a location for a principal's place of birth
When selecting a principal's place of birth, only geographical locations should be available for selection.  Virtual locations, advisor locations and principal locations should not be available for selection.

_Use case 5_: Selecting a location for a principal's residence
When selecting a principal's residence, only geographical locations should be available for selection.  Virtual locations, advisor locations and principal locations should not be available for selection.

**Describe alternatives you've considered**
None

**Additional context**
There are two types of locations:

1. Virtual
2. Physical

**Virtual Locations:**
* ANET currently has nine virtual locations:
* APAN (All Partners Access Network)
* Email Communications
* FaceTime
* Signal App
* Skype
* Telephonic Engagement
* VTC
* WhatsApp
* Zoom

Currently, virtual locations are only used as a location for engagement reports when the advisor and principal do not physically meet.  Virtual locations are only used with engagement reports.

**Physical Locations:**

Physical locations have two sub-types:

1. Geographical
2. Pinpoint

**Geographical Locations:**

A geographical location is a district and a province.  Note: A province has multiple districts.

Geographical locations have two uses:

1. Principal's place of birth
2. Principal's residence 

**Pinpoint Locations:**
Pinpoint locations are a specific place, not a geographical area.  A pinpoint location can be a military base, camp, FOB or building.

Pinpoint locations have two sub-types:

1. Advisor Location
2. Principal Location

**Advisor Locations:**

Advisor locations are always a base, camp or FOB.  An advisor location is never a building.
An advisor location is where advisor's sleep and have their office.  Advisor locations are considered safe from principal insider attacks.  

It goes without saying the advisors sleep at advisor locations and principals do not sleep at advisor locations.

When a principal is TAAed (Train-Advise-Assist) at an advisor location, the engagement is called a "host-to-advise" engagement.

**Principal Locations:**

Principal locations can be a base, camp FOB or a building on a base/camp/FOB.  A principal location is where principal's work and have their offices.  Advisors are subject to principal insider attacks at a principal location.

The significance of a building location is that if there is an emergency, the first place to look for the advisors would be at the building on the principal's base/camp/FOB.  This is a real-time use of ANET.

It goes without saying the advisors do not sleep at principal locations

When a principal is TAAed at a principal location, the engagement is called a "fly-to-advise" engagement.

**Comment by midmarch** [comment]
I propose to categorize locations using hierarchical code:

| Location type code | Description                 |
|--------------------|-----------------------------|
| `P           `     | Phyisical Location          |
| `PG          `     | Geographical Location       |
| `PP          `     | Pinpoint location           |
| `PPA         `     | Pinpoint advisor location*   |
| `PPP         `     | Pinpoint principle location* |
| `V           `     | Virtual location            |

_*I am actually hesitating about `PPA` & `PPP` as these is more a usage then a location type._

The hierarchy allows easy filter, like give me all virtual locations:
```sql
SELECT * FROM locations WHERE locations.type LIKE  'V%';
```
or all pinpoint locations:
```sql
SELECT * FROM locations WHERE locations.type LIKE  'PP%';
```

The usage of a location is part of the many-to-may table holding location and people relations:

```
[table people] <= [table location-relation: relation-type] =>  [table location]
```

Where location type can be:
* place-of-birth
* residence
* ....

**Comment by gjvoosten** [comment]
Plan of approach, first part of the plan addresses use cases 1, 2 and 3:

- [ ] on the server side, add the data model to the database: new table locationTypes ( uuid?, code, description? )
- [ ] on the server side, migrate existing locations: infer the location type by its usage, e.g. if the location has no coordinates, it is virtual; if the location is used for advisor postions, it is an advisor location, etc.
- [ ] on the server side, add location type to the GraphQL schema (both for retrieving and for setting/updating)
- [ ] on the client side, change the location model to show the type as part of the label, and add the location type to tables that show locations
- [ ] on the client side, change the location screens to show/edit the location type
- [ ] on the server side, extend GraphQL schema to allow to search for locations based on type
- [ ] on the client side, add search filters for location types
- [ ] on the client side, change the location filtering for a position's location to use the proper search filter (advisor or principal location)
- [ ] on the client side, change the location filtering for a report's location to use the proper search filter (virtual, … etc.)

Second part of the plan addresses use cases 4 and 5:

- [ ] in the dictionary, add custom fields for principal's place of birth and residence (anet_object of type Location), so now these fields are available for principals (but without restrictions on the location type)
- [ ] in the dictionary/schema, allow for a way to define how this anet_object should be filtered
- [ ] on the client side, use the defined filter(s) to restrict the search
