### ISSUE TITLE
Epic 383 - Enhance code analysis

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#383]
Stories:
- [ ] #3806
- [x] Review the current tool usefulness, and when needed replace tools
- [x] Review build system
- [x] Review changelog generation
