### ISSUE TITLE
Fully use storybook

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#3838]
- Investigate storybook / chromatic concept
   - [ ]  #3850
- [ ] integrate chromatic
- [ ] have coverage for all components
- [ ] mdx documentation
- [ ] update main page
- [ ] bundle doc into ANET

**Comment by gjvoosten** [comment]
Mosly done now, except coverage for all components.
