### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#389]
- [x] #3807
- [x] Update installation instructions to be more robust
- [x] Add Troubleshoot.md
- [x] Document WMS configuration
- [ ] ~~Document SSL certificate request process~~ Moved to [AB#192](https://dev.azure.com/ncia-anet/ANET/_workitems/edit/192)
- [ ] ~~Document sensitive information functionality~~ Moved to [AB#193](https://dev.azure.com/ncia-anet/ANET/_workitems/edit/193)
- [ ] ~~Update workflow document, remove mission references~~ Moved to [AB#194](https://dev.azure.com/ncia-anet/ANET/_workitems/edit/194)
- [ ] ~~Add container installation section (no priority)~~ Moved to [AB#195](https://dev.azure.com/ncia-anet/ANET/_workitems/edit/195)

**Comment by VassilIordanov** [comment]
- [ ] Update installation instructions to be more robust
- [ ] Add Troubleshoot.md
- [ ] Document WMS configuration
- [ ] Document SSL certificate request process

**Comment by midmarch** [comment]
All tasks implemented or covered in ANET Azure Boards
