### ISSUE TITLE
Epic Improve layout

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#551]

**Comment by VassilIordanov** [comment]
- [ ] Add context-sensitive action toolbars, possibly with sticky layout
- [ ] Make layout responsive
- [ ] Make layout use all available space
